name: Docker build and push
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 2 * * 0"

env:
  DOCKER_BUILDKIT: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile
          config: hadolint-ci.yaml

  push:
    runs-on: ubuntu-latest
    needs: lint
    if: github.event_name != 'pull_request'
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker-compose -f docker-compose.yml build python

      - name: Log into registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login https://index.docker.io/v1/ -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push image
        run: docker-compose -f docker-compose.yml push python

      - name: Tag build-versioned image
        run: docker tag acornsaustralia/python acornsaustralia/python:${{ github.run_number }}

      - name: Push versioned image
        run: docker push acornsaustralia/python:${{ github.run_number }}
